name: Reusable workflow
on:
  repository_dispatch:
    types: [org-workflow-bot]
    
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
      with:
        repository: ${{ github.event.client_payload.repository.full_name }}
        ref: ${{ github.event.client_payload.sha }}
        token: ${{ github.event.client_payload.token }}
    - name: Markdown Lint
      uses: ruzickap/action-my-markdown-linter@v1
